### ISSUE TITLE
xliff 1.2 generated by WPML (Wordpress plugin) not parsed

### ISSUE THREAD

**Issue by digitalica** [locize/xliff#1]
XLIFF like the below, generated by WPML is not parsed correctly. The system expects 
```xml
<segment>
```
elements in
```xml
<unit>
```
elements...

And the XLIFF 1.2 from WPML looks different:

```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
<file original="1842-43fa4a29d62b66b56d7b5c5e055bbad5" source-language="nl" target-language="en" datatype="plaintext">
<header><reference><external-file href="http://www.domain.nl/somepage/"/></reference></header>
<body>
  <trans-unit id="key2">
    <source>hallo</source>
    <target>hallo</target>
  </trans-unit>
</body>
</file>
</xliff>
```

**Comment by adrai** [comment]
Yes, unfortunately this module only works for xliff version 2 format right now... :-(

**Comment by digitalica** [comment]
I needed to do some modifications in a larger set of XLIFF files, so just read them as text files for now... 

I'd like to build a tool for XLIFF manipulation (like creating different types of pseudo-translations, analysing number of translated / blank / equal segments, finding (and fixing) Wordpress specific stuf like shortcodes and/or urls etc. Main thing i'd like to be able to do is write a modified xliff in almost the exact format it was read, except for the changes of course.

You think this module could/should support other xliff versions too? Or would you prefer a separate module?

**Comment by adrai** [comment]
feel free to submit a pull request ;-)

**Comment by adrai** [comment]
try v1.0.0 => has xliff v1.2 support ;-)

**Comment by Fabiomad85** [comment]
Same problem here.
