### ISSUE TITLE
XLIFF to JS conversion error { Error: Text data outside of root node.

### ISSUE THREAD

**Issue by matt212** [locize/xliff#17]
Hi @adrai , 

I am able to create successfully XLIFF files using `xliff/js2xliff` and it worked as expected.
now i wanted to convert same XLIFF to js using `xliff/xliff2js`  . but i am getting below error

![yarn import](https://user-images.githubusercontent.com/1698139/45998249-e9499400-c0bf-11e8-8269-02b9d0c331ba.png)

**code** 
`xliff2js('./1537854025565.xml', (err, res) => {
  if (err) {
    console.log(err)
  }
  console.log(res)
})

`
Please note the XLIFF generated is valid .
Should i read XLIFF  first to string and then pass it on xliff2js fuction ?

**Comment by adrai** [comment]
exactly, like in the readme 😜
