### ISSUE TITLE
Support for multiple <segment>s

### ISSUE THREAD

**Issue by kaidjohnson** [locize/xliff#22]
Thanks for this library! Very useful!

I noticed a few features in the XLIFF 2.0 spec (http://docs.oasis-open.org/xliff/xliff-core/v2.0/os/xliff-core-v2.0-os.html) that do not appear to be implemented, namely the use of multiple `<segment>` entries. Any thoughts around if this feature may be supported in the future? 

As a workaround for now, we can combine our `<segment>`s into a single `<segment>`, but would be nice to continue to maintain multiple in the future.

**Comment by adrai** [comment]
Currently there is/was no need for this.
Do you have an idea how a json file could look like?
Btw: if you want to contribute, feel free to suggest a PR

**Comment by ph-fritsche** [comment]
I just stumbled over this in a project.
What do you think about this?
```xliff
<unit id="foo">
  <segment>
   <source>some source paragraph</source>
   <target>some target paragraph</target>
  </segment>
  <segment>
   <source>another source paragraph</source>
   <source>another target paragraph</target>
  </segment>
</unit>
```
through `xliff2js` and `targetOfjs` this could produce
```json
foo: [
  "some target paragraph",
  "another target paragraph",
]
```

This would allow to use this e.g. in React like this:
```jsx
<div>{t('foo').map(t => <p>{t}</p>)}</div>
```

**Comment by adrai** [comment]
Feel free to try a PR.
