### ISSUE TITLE
Google Actions xliff elements

### ISSUE THREAD

**Issue by armonge** [locize/xliff#26]
I'm trying to generate an xliff 1.2 file for use with google actions, however seems like there's no support for one of the elements google actions uses, specifically the "group" element. I have a working implementation that adds support for this, would you be open to a contribution?

https://developers.google.com/assistant/console/publish-localized
http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#group

**Comment by adrai** [comment]
for sure... contributions are always welcome.
Have a try and create a PR.
Just make sure you will not brake the existing compatibility.

**Comment by adrai** [comment]
Landed in v4.4.0 👍
