### ISSUE TITLE
xliff12ToJs ingnoring nested groups

### ISSUE THREAD

**Issue by amadare42** [locize/xliff#28]
## 🐛 Bug Report

`xliff12ToJs()` result will omit `group`s that are nested in other `group`. 

## To Reproduce

sandbox: https://codesandbox.io/s/heuristic-leavitt-vsumc?file=/src/index.js

## Expected behavior

`group`s inside of `group`s is valid structure according to spec: (http://docs.oasis-open.org/xliff/v1.2/cs02/xliff-core.html#group).
Therefore, I expect property inside of `group` that represents nested `group`s.

## Your Environment

- *module version*: >=5.0.6

**Comment by adrai** [comment]
Would you like to try a PR?

**Comment by adrai** [comment]
// cc @spencerfdavis

**Comment by probertson** [comment]
This looks pretty straightforward. I'm working on this now.

**Comment by adrai** [comment]
released with v5.1.0
