### ISSUE TITLE
Add seamless conversion between XLIFF and i18next JSON

### ISSUE THREAD

**Issue by sffc** [locize/xliff#33]
## 🚀 Feature Proposal

I would like to convert back and forth between [i18next JSON](https://www.i18next.com/misc/json-format) and XLIFF, including the appropriate representation of placeholders, plurals, etc.

Currently, you convert the XLIFF back and forth to an XLIFF-like JSON structure:

```javascript
{
  "resources": {
    "namespace1": {
      "key1": {
        "source": [
          "Hello ",
          {
            "GenericSpan": {
              "id": "name",
              "ctype": "x-python-brace-param",
              "contents": "{name}"
            }
          }
        ],
        "target": [
          "Hallo ",
          {
            "GenericSpan": {
              "id": "name",
              "ctype": "x-python-brace-param",
              "contents": "{name}"
            }
          }
        ]
      },
      // ...
    }
  },
  "sourceLanguage": "en-US",
  "targetLanguage": "de-CH"
}
```

However, the format I want to use is the i18next JSON format, like this:

```javascript
{
  "namespace1.key1": "Hello {{name}}"
}
```

I want the placeholder to be automatically converted to/from the XLIFF GenericSpan.

## Motivation

I want to send XLIFF files off to my translation service, and use i18next to power my app.

## Example

Something along the lines of `xliff/createxliff` and `xliff/createjs`, but which interact using the i18next format instead of the current XLIFF-like JSON format.

**Comment by adrai** [comment]
You first need to execute xliff2js and then targetOfJs or sourceOfJs, like: https://github.com/locize/locize-cli/blob/master/convertToFlatFormat.js#L187

**Comment by tkforce** [comment]
Hi @adrai,

We're also using i18next while working with translation company that only support XLIFF format, so conversion between XLIFF and i18next JSON is essential.

By reading through the doc and comments in this thread https://github.com/locize/xliff/issues/47, it sounds like you're suggesting:

**i18next JSON -> XLIFF**  

1. First flatten the JSON using something like [flat](https://www.npmjs.com/package/flat).
2. Use `xliff.createxliff` to create XLIFF using the flattened i18next JSON.

**XLIFF -> i18next JSON**  
1. First use `xliff.xliff2js` to convert XLIFF to an XLIFF-like JSON.
2. Use `targetOfjs ` to convert this XLIFF-like JSON to i18next JSON.

Why is this XLIFF-like JSON format exist at all if i18next JSON is the one we need?

**Comment by adrai** [comment]
> Why is this XLIFF-like JSON format exist at all if i18next JSON is the one we need?

Sorry @tkforce I don't really understand your question.

Regarding your described workflow, yes, this is more or less also what can be done. (it may be you need to unflatten the resulting JSON at the end, if you're using a nested json format)

btw: This xliff module will only create an xliff file format used as translation container. The originally used i18n format (in your case i18next) will always be respected, there is no sort of i18n format conversion. This means if you're using multiple plural forms (https://www.i18next.com/translation-function/plurals#languages-with-multiple-plurals) these will NOT get converted to a more xliff friendlier i18n format, like for example ICU Message Format...
