### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by terales** [locize/xliff#36]
## 🚀 Feature Proposal

Hi, thanks for a parser!
Would you accept a PR with a default MIT License file, so the GitHub repository would correctly recognize it?

## Motivation

Making sure that dependency licenses are from the accepted range is a requirement in many companies.

## Example

Here is how GitHub would present it after the License would be added:
![image](https://user-images.githubusercontent.com/1920639/105506535-d9afd980-5cd2-11eb-8fe5-6d1b92b704d2.png)

**Comment by adrai** [comment]
Thank you... should have done this already ;-)
