### ISSUE TITLE
When there are XML comments in the XLIFF document, xliff2js throws an error

### ISSUE THREAD

**Issue by NullVoxPopuli** [locize/xliff#37]
## 🐛 Bug Report

Comments cause an error in `createUnits` while iterating over elements.

## To Reproduce

Reproduction: https://runkit.com/nullvoxpopuli/xliff-library-can-t-handle-comments
```js
const xliff = require('xliff');
let xml = `<xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en-us" trgLang="en-us">
  <file id="file/path/wooo">
    <!-- comment a -->
    <unit id="foo"><segment><target>woosh</target></segment></unit>
  </file>
</xliff>`;

xliff.xliff2js(xml, (err, res) => {})

```
![image](https://user-images.githubusercontent.com/199018/111010324-28d5ca80-8364-11eb-8f5b-364f6d9ae4ad.png)

## Expected behavior

No error

**Comment by NullVoxPopuli** [comment]
Work around for now:
```js
let withoutComments = xml.replace(/<!--[^-]*-->/g, '')

xliff.xliff2js(withoutComments, (err, res) => {})
```

**Comment by adrai** [comment]
Can you try with v5.5.1 ?

**Comment by NullVoxPopuli** [comment]
Updated the reproduction. Same error, different location of trace.

**Comment by adrai** [comment]
next try with v5.5.2 ;-)

**Comment by NullVoxPopuli** [comment]
Both commits from both those versions don't have tests :/

Would a failing test PR be helpful?

**Comment by NullVoxPopuli** [comment]
That fixed it though. And proved via v4 of the runkit: https://runkit.com/nullvoxpopuli/xliff-library-can-t-handle-comments

**Comment by adrai** [comment]
Tests are added ;-)
