### ISSUE TITLE
Support for `additionalAttributes` on target

### ISSUE THREAD

**Issue by dbo** [locize/xliff#41]
## 🚀 Feature Proposal

There's a way to use define inline elements for target via the JS API, but I don't find a way to define additional attributes on such.

## Motivation

For instance, defining the translation state on a target, http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#target

## Example

AFAIS, source and target could be either a string or an array (inline elements). Allowing a structured object could define attributes e.g.
```js
target: {
  content: "Hallo",
  additionalAttributes: {
    state: "new",
  }
}
```

**Comment by adrai** [comment]
Please check out this example: https://github.com/locize/xliff#additional-attributes-example

**Comment by adrai** [comment]
Or do you mean attributes on the `<target>` element? like this: `<target some="attr">` ?
// cc: @probertson

**Comment by dbo** [comment]
yes, I mean attributes on `<target>`

**Comment by zatloeri** [comment]
I would even extend this need to all elements. I need to add custom attributes to almost everything and it is the only limitation of this library for me which prevents me from using it. And because I need it asap, I need to fork.

**Comment by adrai** [comment]
> I would even extend this need to all elements. I need to add custom attributes to almost everything and it is the only limitation of this library for me which prevents me from using it. And because I need it asap, I need to fork.

If you like you can also contribute with a PR.

**Comment by zatloeri** [comment]
> > I would even extend this need to all elements. I need to add custom attributes to almost everything and it is the only limitation of this library for me which prevents me from using it. And because I need it asap, I need to fork.
> 
> If you like you can also contribute with a PR.

I might if I have some spare time. For now I forked and I am just implementing the part that I immediately need and want (`jsToXliff12`) and then I will have a look into how hard would it be to implement it for the rest.
