### ISSUE TITLE
Adding support for metadata module

### ISSUE THREAD

**Issue by gl0dt** [locize/xliff#44]
## 🚀 Feature Proposal

Adding support for metadata module

## Motivation

Metadata comes handy for saving customized data/attributes that doesn't belong to other tags

## Example

```
 <mda:metadata>
   <mda:metaGroup category="document_xml_attribute">
     <mda:meta type="version">3</mda:meta>
     <mda:meta type="phase">draft</mda:meta>
   </mda:metaGroup>
 </mda:metadata>
```

**Comment by adrai** [comment]
Have no idea how to map this to json, but feel free to submit a PR.
