### ISSUE TITLE
Place <note> inside <notes> section of the <unit>

### ISSUE THREAD

**Issue by mxs17** [locize/xliff#45]
Hello!

I am trying to generate xliffs for Memsource. Everything works well except for `<note>` blocks. If I supply something like:
```json
{
  "resources": {
    "units": {
      "unit-id": {
        "source": "Some source text",
        "target": "",
        "note": "Some note"
      }
    }
  },
  "sourceLanguage": "en",
  "targetLanguage": "ru"
}
```
into js2xliff, I will get:
```xml
<xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en" trgLang="ru">
  <file id="units">
    <unit id="unit-id">
      <segment>
        <source>Some source text</source>
        <target></target>
        <note>Some note</note>
      </segment>
    </unit>
  </file>
</xliff>
```
while Memsource (and, I believe, the xliff spec too) expects `<notes>...</notes>` section on the unit level:
```xml
<xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en" trgLang="ru">
  <file id="units">
    <unit id="unit-id">
      <notes>
        <note>Some note</note>
      </notes>
      <segment>
        <source>Some source text</source>
        <target></target>
      </segment>
    </unit>
  </file>
</xliff>
```
Is it possible to generate these `<notes>...</notes>` sections with the current version of xliff library? If not, can we implement this feature?

**Comment by adrai** [comment]
@AlexanderNoskov can you have a look at this?

**Comment by adrai** [comment]
@mxs17 can you try with v5.6.1?

**Comment by adrai** [comment]
fyi: this was the change: https://github.com/locize/xliff/commit/5f742b3c6d8c6f732c4d23652c46e93feb172f5b

**Comment by mxs17** [comment]
@adrai, thanks! I think the xliff is correct now, but it looks like Memsource expects `<notes>` before the `<segment>`. I am not sure if their requirement is reasonable, by this is how it works now. I moved `<notes>` manually, and the file was successfully imported.

The warning with `<notes>` after the `<segment>`:

_Invalid xliff 2.0: Error systemId: lineNumber: 8; columnNumber: 14; cvc-complex-type.2.4.a: Invalid content was found starting with element 'notes'. One of '{"urn:oasis:names:tc:xliff:document:2.0":segment, "urn:oasis:names:tc:xliff:document:2.0":ignorable}' is expected._

_Invalid xliff 2.0: Error systemId: lineNumber: 9; columnNumber: 14; cvc-complex-type.2.4.a: Invalid content was found starting with element 'notes'. One of '{"urn:oasis:names:tc:xliff:document:2.0":segment, "urn:oasis:names:tc:xliff:document:2.0":ignorable}' is expected._

**Comment by adrai** [comment]
strange, this should not be a problem, but ok...
can you try with v5.6.2 ?

**Comment by mxs17** [comment]
With v5.6.2, the xliff is imported flawlessly. Thank you very much!

**Comment by adrai** [comment]
ok, good it worked.
btw: In case you want to tell me why you're using memsource instead of locize.com as translation management or localistars.com for the translation work, please write an e-mail at support@locize.com
