### ISSUE TITLE
Convert JSON to XLIFF without translating

### ISSUE THREAD

**Issue by jrmcdona** [locize/xliff#47]
Hello-
I didn't see a way to simple take a JSON file and covert it to XLIFF.  Is there a way?

It looks like the tool is for converting and translating at the same time.

I have many JSON files,  I want to convert them to XLIFF. 

I will then send the XLIFF files to my localization team.

Thanks

**Comment by adrai** [comment]
js2xliff is probably what you need, transforms [this](https://github.com/locize/xliff/blob/master/test/fixtures/example.json) into [this](https://github.com/locize/xliff/blob/master/test/fixtures/example.xliff)

or use [locize](https://locize.com)... [import your json files](https://docs.locize.com/more/general-questions/how-to-import-translations-from-a-file) and export them with [xliff format](https://docs.locize.com/integration/supported-formats#xliff-2.0).

**Comment by adrai** [comment]
Sorry, I have no idea what you mean by: “it does translate”…
there is no translation, no machine or google translation involved here.

**Comment by adrai** [comment]
Then just omit the target language:

i.e. js2xliff

```js
import xliff from 'xliff'

const js = {
  "resources": {
    "namespace1": {
      "key1": {
        "source": "Hello"
      },
      "key2": {
        "source": "An application to manipulate and process XLIFF documents"
      },
      "key.nested": {
        "source": "XLIFF Data Manager"
      }
    }
  },
  "sourceLanguage": "en-US"
}

xliff.js2xliff(js, (err, ret) => {
  if (err) console.error(err)
  console.log(ret)
})

```

or createxliff:

```js
import xliff from 'xliff'

xliff.createxliff(
  'en-US',
  undefined,
  {
    "key1": "Hello",
    "key2": "An application to manipulate and process XLIFF documents",
    "key.nested": "XLIFF Data Manager"
  },
  undefined,
  'namespace1', (err, ret) => {
    if (err) console.error(err)
    console.log(ret)
  }
)

```

**Comment by jrmcdona** [comment]
But it is not in that format.   It just a JSON file that I am trying to convert to XLIFF.

Assuming I need to convert to your format of JSON for this to work?

Example:

{
  "sortBy": {
    "label": "Sort by",
    "Ascending": "Relevance",
    "Descending": "Date"
},
"notFound": {
    "heading": "We are sorry, the page you requested cannot be found.",
    "paragraph": "The URL may be misspelled or the page you're looking for is no longer available."
},
"feedback": {
  "label": "Was this information useful?",
  "ariaLabel": "If you would like to provide feedback, please complete this survey."
},
"blog": {
    "byText": "By ",
    "readMore": {
        "label": "Read more",
        "ariaLabel": "Read more about"
    },
    "relatedPosts": {
      "label": "Related posts",
      "linkText": "View all",
      "linkAriaLabel": "View all related posts",
      "postsByText": "Posts by "
    },
    "loadMore": {
        "label": "Load more",
        "ariaLabel": "Load more items"
    },
    "backToListText": "Back to articles",
    "backToListAriaLable": "Back to listings",
    "publishedOnText": "Published on",
    "publishedByText": "by",
    "publishedInText": "in",
    "signUp": {
        "title": "Sign up for our newsletter",
        "contentText": "Receive news and program updates in your inbox.",
        "linkTitle": "Sign up now"
    },
    "twitter": {
      "title": "Follow us on Twitter",
      "contentText": "Join a growing community of experts who help shape the future of Office.",
      "linkTitle": "Connect with us"
  }
},
"releaseNotes": {
    "heading": "Office Insider Release Notes",
    "tabsAriaLabel": "Release notes tab per platform",
    "paragraph": "Every week or month (depending on your Insider level), we'll highlight interesting new features, important fixes, and any significant issues we want you to know about. We often roll out features to Insiders over a period to ensure that things are working smoothly. So, if you don't see something described here, don't worry, you'll get it eventually.",
    "readMore": {
        "label": "Read more",
        "ariaLabel": "Read more about"
    },
    "loadMore": {
        "label": "Load more",
        "ariaLabel": "Load more items"
    },
    "backToListText": "Back to articles",
    "backToListAriaLable": "Back to listings",
    "publishedOnText": "Published on",
    "publishedByText": "by",
    "publishedInText": "in",
    "onThisPageText": "On this page",
    "takeACloserLook": {
     "title": "Take a closer look",
     "subTitle": "Explore the latest features",
     "linkText": "Visit the Office Insider blog",
     "ariaLabel": "Click here to visit the Office Insider blog"
    }
},
"featuredHighlights": {
  "displayName": "business-featured-highlights-nav",
  "heading": "Explore Office Insider features for business",
  "paragraph": "We are building new features and experiences to increase productivity, save time, and revolutionize the way you work. Take a look at some of the features that have been designed with you, our business customers, in mind. Some are available broadly today, others are coming soon. Be sure to come back and check for updates.",
  "navLinks": [
    {
      "navLink": {
        "linkText": "All",
        "ariaLabel": "All platforms",
        "destinationUrl": "#"
      }
    },
    {
      "navLink": {
        "linkText": "Windows",
        "ariaLabel": "Windows",
        "destinationUrl": "#"
      }
    },
    {
      "navLink": {
        "linkText": "Mac",
        "ariaLabel": "Mac",
        "destinationUrl": "#"
      }
    },
    {
      "navLink": {
        "linkText": "iOS",
        "ariaLabel": "iOS",
        "destinationUrl": "#"
      }
    },
    {
      "navLink": {
        "linkText": "Android",
        "ariaLabel": "Android",
        "destinationUrl": "#"
      }
    }
  ],
  "paragraph1": "We are building new features and experiences to increase productivity, save time, and revolutionize the way you work. Take a look at some of the features that have been designed with you, our business customers, in mind. Some are available broadly today, others are coming soon. Be sure to come back and check for updates.",
  "header": "Explore Office Insider features for business"
},
"search": {
  "text": "Searching for:",
  "result": "results"
},
"join": {
  "tabsAriaLabel": "Join information tabs per platform",
  "heading": {
    "text": "Join the Office Insider Program",
    "content": "Be the first to see what's next for Office, give us your feedback to help us improve Office for the future, and join our inspiring community in the Office Insider Program.",
    "note":  "Note: Office Insider is installed on each device separately."
  },
  "backgroundImage": {
    "vp5": "https://prodmediacdn.blob.core.windows.net/media/2020/06/landscape_vp5_800x450_0000s_0001_GettyImages-1144533673.jpg.jpg",
    "vp4": "https://prodmediacdn.blob.core.windows.net/media/2020/06/landscape_vp4_630x449_0000s_0001_GettyImages-1144533673.jpg.jpg",
    "vp3": "https://prodmediacdn.blob.core.windows.net/media/2020/06/landscape_vp3_561x421_0000s_0001_GettyImages-1144533673.jpg.jpg",
    "vp2": "https://prodmediacdn.blob.core.windows.net/media/2020/06/landscape_vp2_859x557_0000s_0001_GettyImages-1144533673.jpg.jpg",
    "vp1": "https://prodmediacdn.blob.core.windows.net/media/2020/06/landscape_vp1_539x349_0000s_0001_1144533673.jpg",
    "altText": "woman on phone"
  },
  "leftmenuTitle": {
    "title": "On this page"
  }
},
"handbook": {
   "leftmenuTitle": {
    "title": "On this page"
  }
},
"forbusiness": {
    "title": "Getting started on deploying Office Insider builds",
    "description": "We're so glad you've made the decision to bring Office Insider Preview builds into your organization. There are a variety of different methods to deploy these preview builds. Choose the right one for your workplace below and start exploring the latest innovations in Microsoft 365."
  },
  "bizoverview":{
    "title": "The Office Insider Program ​for Business​",
    "description": "Office Insider builds provide organizations with a variety of installation options and offer an effective way to explore Office features prior to your next Office deployment. <a href=\"/business/deploy/\">Get Started ></a>"
  },
  "deploy": {
    "alert": {
      "heading": "Looking for a tutorial? We have a video at the bottom of this page that describes how to deploy the Office Insider program in your organization.",
      "ariaLabel": "Learn more in the  video tutorial.",
      "linkText": "Learn more."
    },
    "video": {
      "heading": "How to Deploy the Office Insider Program in your Organization",
      "paragraph": "Check out this video to get the basics about the Office Insider program and learn how to install it via ODT, Intune and Group Policy."
    }
  }
}
