### ISSUE TITLE
Convert from json to XLIFF with CDATA

### ISSUE THREAD

**Issue by frandieguez** [locize/xliff#48]
## 🚀 Feature Proposal

Allow to produce XLIFF 2 or XLIFF 1.1 with all translations inside a CDATA.

## Motivation

We have a bunch of react-i18next json strings with embed HTML that we want to convert to xliff js2Xliff function escapes the html tags. 

We would like to generate an XLIFF file without all those tags escaped but wrapped inside a CDATA

## Example

```
{
  "string_to_translate" : "<strong>Careful!</strong> You are going to delete the following task.",
}
```

Desired output

```
<xliff xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 http://docs.oasis-open.org/xliff/v1.2/os/xliff-core-1.2-strict.xsd" xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file original="situm" datatype="plaintext" source-language="en" target-language="en">
    <body>
      <trans-unit id="1" resname="string_to_translate">
        <source><![CDATA[strong>Careful!</strong> You are going to delete the following task.]]></source>
        <target><![CDATA[strong>Careful!</strong> You are going to delete the following task.]]></target>

```

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this with an option? Remember to add unit tests.

**Comment by frandieguez** [comment]
I'll try to make a PR this weekend
