### ISSUE TITLE
targetOfjs does not convert groups

### ISSUE THREAD

**Issue by marmarosi** [locize/xliff#49]
## 🐛 Bug Report

Function targetOfjs does not convert groups.

## To Reproduce

Using your sample Xliff 2.0 data:
```js
const file = path.resolve(__dirname, './sample.xlf');
const xliff = fs.readFileSync(file).toString();
const js = await xliff2js(xliff);
const target = targetOfjs(js);
console.log(target);
```
The output is:
```js
{
  key1: 'Hallo',
  key2: 'Eine Applikation um XLIFF Dokumente zu manipulieren und verarbeiten',
  'key.nested': 'XLIFF Daten Manager',
  group: undefined
}
```

## Expected behavior

I would expect the following output:
```js
{
  key1: 'Hallo',
  key2: 'Eine Applikation um XLIFF Dokumente zu manipulieren und verarbeiten',
  'key.nested': 'XLIFF Daten Manager',
  group: {
    groupUnit: 'Gruppe'
  }
}
```

## Your Environment

- *runtime version*: node v16.13.0
- *module version*: >=5.7.2
- *os*: Windows

**Comment by adrai** [comment]
Yes, this was intensional. Only "normal" segments are handled with the OfJs functions.
But if you think it is a general good idea to have also the group segments, you can try a PR introducing a option argument, something like: `targetOfjs(js, { includeGroups: true }, cb)` or similar...?
