### ISSUE TITLE
'State' attribute missing from converted xliff files

### ISSUE THREAD

**Issue by Andrew-Marks-Trisept** [locize/xliff#51]
## 🐛 Bug Report

After converting from xliff to json and back, the xliff file is missing certain attributes, such as `state` on `<segment>` nodes.  `state` in particular is important for other translation software when working with the xliff files.

## To Reproduce

We have a complex multi-site app using Angular, so we are using this library to merge and edit the xliff files that Angular generates initially.  An example use case would be to read an xliff file into JS, remove certain `<unit>` nodes, then write the contents to a different xliff file, but a barebones case is:

```js
var fs = require("fs");
var util = require("util");
var xliff = require("./modules/xliff");
var readFile = util.promisify(fs.readFile);

processMessageFile("./src/locale/base-messages/messages.es-MX.xlf");

async function processMessageFile(filePath) {

  //Read xlf file and convert to JS
  var fileContent = await readFile(filePath, "utf8");
  var jsContent = await xliff.xliff2js(fileContent);

  //Normally we'd manipulate jsContent here, but it doesn't matter

  //Convert back to xlf and replace file contents
  var newXlf = await xliff.js2xliff(jsContent);
  await writeFile(filePath, newXlf);
}

async function writeFile(path, content) {
  fs.writeFile(path, content, "utf8", function (err) {
    if (err) {
      return console.log(err);
    }
  });
}
```

Below is an example message file with one translated message and one non-translated message.

**Before:**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xliff version="2.0" xmlns="urn:oasis:names:tc:xliff:document:2.0" srcLang="en-US" trgLang="es-MX">
  <file id="ngi18n" original="ng.template">
    <unit id="core.pageTitles.account">
      <notes>
        <note category="location">src/app/account/account-routing.module.ts:13</note>
      </notes>
      <segment state="translated">
        <source>My Account</source>
        <target>Mi cuenta</target>
      </segment>
    </unit>
    <unit id="core.pageTitles.account.reservations">
      <notes>
        <note category="location">src/app/account/account-routing.module.ts:19</note>
      </notes>
      <segment state="initial">
        <source>Reservations</source>
        <target>Reservations</target>
      </segment>
    </unit>
  </file>
</xliff>
```

**After:**
```xml
<xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en-US" trgLang="es-MX">
  <file id="ngi18n">
    <unit id="core.pageTitles.account">
      <notes>
        <note>src/app/account/account-routing.module.ts:13</note>
      </notes>
      <segment>
        <source>My Account</source>
        <target>Mi cuenta</target>
      </segment>
    </unit>
    <unit id="core.pageTitles.account.reservations">
      <notes>
        <note>src/app/account/account-routing.module.ts:19</note>
      </notes>
      <segment>
        <source>Reservations</source>
        <target>Reservations</target>
      </segment>
    </unit>
  </file>
</xliff>
```

You can see that afterwards there is no way to tell which ones are already translated.

## Expected behavior

The only thing I really care about at the moment is that `<segment>` nodes should maintain their `state` attribute.  This is important so that translators working with these files (using a translation tool like Poedit, BabelEdit, etc) know which messages have already been translated and which need attention.  We don't want to redo our whole manual translation process each time the file is regenerated or merged to.

Other than that, I'm assuming that, ideally, no attributes or other nodes would be removed.  But I don't think this is actually causing me any issues the moment.  For example, I noticed that:

- `<?xml version="1.0" encoding="UTF-8"?>` is removed.
- The `original` attribute on `<file>` is removed.
- The `category` attribute on `<note>` is removed.  I think this may be useful for certain tools that can link translations to their location in the Angular code, but I'm not sure.

## Your Environment

- *node*: v16.13.1
- *xliff*: tested with v5.7.2 and 6.0.0
- *os*: Windows 10

**Comment by jamuhl** [comment]
The primary purpose of this module is to work with our own translation management product https://locize.com which does not rely on the state attribute at all.

Not sure if @adrai is open to accept a pull request to address this.

**Comment by adrai** [comment]
Can confirm what @jamuhl is saying...
Nevertheless, there already is support for additionalAttributes, like described here: https://github.com/locize/xliff#additional-attributes-example
If you like to provide a PR to extend this, without introducing any breaking change, feel free. Probably also @cietho will review it?

**Comment by Andrew-Marks-Trisept** [comment]
@adrai Sorry, I don't understand the point about additionalAttributes.  In my case the attributes are already there in the initial xlf, so what would I be adding?  The documentation says it works in both directions, but I'm suspecting maybe it only supports additional attributes on `<unit>`?

**Comment by adrai** [comment]
exactly
