### ISSUE TITLE
xliff12ToJs() looses spaces between inline elements

### ISSUE THREAD

**Issue by TheSlimvReal** [locize/xliff#55]
## 🐛 Bug Report

I have a translation unit with just a space between two inline elements. When parsing this with `xliff12ToJs` the space is lost and I end up with an array of only the two inline elements.

## To Reproduce
This is the snipped which I am using (created using Angulars `extract-i18n`.
```html
<trans-unit id="3036695099328175425" datatype="html">
  <source><x id="PH" equiv-text="..."/> <x id="PH_1" equiv-text="..."/></source>
  <target state="translated"><x id="PH" equiv-text="..."/> <x id="PH_1" equiv-text="..."/></target>
</trans-unit>
```

## Expected behavior

The resulting array should contain 3 elements, the two inline elements and the space-string in between.

**Comment by adrai** [comment]
@probertson can you help?

**Comment by adrai** [comment]
btw:: you may try with CDATA

```xml
<trans-unit id="3036695099328175425" datatype="html">
  <source><x id="PH" equiv-text="..."/><![CDATA[ ]]><x id="PH_1" equiv-text="..."/></source>
  <target state="translated"><x id="PH" equiv-text="..."/><![CDATA[ ]]><x id="PH_1" equiv-text="..."/></target>
</trans-unit>
```

**Comment by adrai** [comment]
with v6.1.0 you can also try with:

```js
xliff12ToJs(js, { captureSpacesBetweenElements: false }, (err, res) => { })
```
