### ISSUE TITLE
Xliff 1.2 doesn't use srcLang and trgLang

### ISSUE THREAD

**Issue by zbrox** [locize/xliff#7]
According to Xliff 1.2 specs the attributes specifying the source and target language are on each file element and are called source-language and target-language. The change to the <xliff> attributes srcLang and trgLang was made with Xliff 2.0. 

Now if you try to parse an Xliff 1.2 like for example exported by Xcode you will have undefined values for source and target language.

**Comment by adrai** [comment]
@spencerfdavis can you confirm?

**Comment by zbrox** [comment]
You can checkout the section "General structure" in the 1.2 specs at http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html

I couldn't find srcLang or trgLang mentioned anywhere in the spec. It shows up in the 2.0 specs. I haven't dug in deeper than this, so somebody else should definitely confirm.

**Comment by probertson** [comment]
I just looked this up in the spec and found the same thing.

**Comment by jamuhl** [comment]
published in xliff@2.0.0
